<script setup lang="ts">

</script>

<template>
  <div class="p-2 w-full">
    <p class="card-bg-title">Plot</p>
    <p class="card-bg-subtitle">Exposition</p>
    <p class="no-card">The Book introduces us to the bill of life. A bill that ensures life to the age of 13 and then you can be unwound by you parents or if you live in a state ward by the government until you turn 18. The book describes unwinding as living in a divided state. We meet the main characters, Connor, Risa, and Lev. Who all have been unwound for different Reasons (See the <a href="#/Characters" class="text-blue-600 underline">Characters</a> Page)</p>
    <p class="card-bg-subtitle">Rising Action</p>
    <p class="no-card">The Main Characters all meet up in a stroke of faith at a crash on the high way. Lev gets pulled out of his vehicle and taken as a hostage. Connor, Lev, and Risa Run into the woods. Lev thinking that he has been captured. Eventually while running from the police they end up at a high school with a baby. Where Lev (Who still wants to be "Tithed" or unwound) reports them for "Takeing him hostage" even though Connor and Risa are trying to save him. Connor and Risa meet Hanna a teacher who takes the baby and tells them of a safe house for unwinds at the antique shop.</p>
    <p class="no-card">Connor and Risa head to the Antique shop where they meet Sonia who invites them into the safe house. In the safe house they meet Hayden as well as Roland who is a sort of side antagonist. Over the next few weeks they move from safe house to safe house. There is rumor that at the end of line is a place called the graveyard.</p>
    <p class="card-bg-contrast">Meanwhile Lev meets a boy named Cyrus Finch, Who goes by Ci-Fy. We learn that Cyrus has part of an unwinds brain and instead of having a bunch of little pieces of brain (like normal) he has a whole lobe which makes him a little insane. The part of the Brain that is not his has a strong desire to go to Joplin Missouri so for better or for worse they make there way there. When they arrive things start to click into place for Cyrus. Joplin was his home. No, it was Tyler Walkers home. Although Cyrus is a minor character in Unwind he serves a propose. He shows reader the downfalls of unwinding and highlights another reason it should be abolished</p>
    <p class="no-card">Connor and Risa soon discover that Roland is what you would call "a pain in the arse" but Connor sees that Roland is more than just the playground bully. Finally they make it to the graveyard on a plane that is about to be decommissioned. They meet the Admiral who served in the Heartland. Connor is wary of him and doesn't like how his teeth are so shiny. They meet "The Goldens" who are the admiral's favorite's. We also here about Cleaver who is the Admirals helicopter Pilot, and Connor is concerned to learn that Roland is training with him. After a few weeks at the Graveyard Lev arrives on one of the incoming ships. How did he get there? Your guess is as good as mine.</p>
    <p class="no-card">One day the admiral call's Connor up to his plane (They live in the decommissioned planes of the graveyard) an old Air Force one. And Revels that the Goldens have been killed and he needs help to find the perpetrator. Connor suspects Roland but Lev has been acting very strange. The next day Lev agrees to go to Alaska to work on an underground pipeline. Connor and Risa no something is up because it is not a desirable job.</p>
    <p class="no-card">Tension starts to rise in the graveyard with rolland leading them to suspect that the admiral is not who he says he is. When word gets out that the admiral has been lying about what actually happened to the Goldens the tension turns into riot. While Connor is interrogating Roland about the Goldens the camp revolts against the admiral leaving him stuck in the plane on a hot arizonian day. When Connor gets there and stops the Riot he finds Risa trying to revive the admiral in the hot plane. Cleaver is outside and dies but not before revealing that he killed the Goldens. Connor and Risa convince Roland to fly the helicopter to the hospital to save the Admiral.</p>
    <p class="card-bg-subtitle">Climax</p>
    <p class="no-card">When they reach the hospital they are ratted out by Roland who thinks he can get away if he tells the Cops about the Unwind camp. The Cops reveal that they already know about the camp and where just two lazy to do anything about it. Connor, Risa, and Roland are all sent to be unwound at Happy Jack harvest camp. </p>
    <p class="no-card">While there they discover that Lev is also there posing as a tithe he has become a clapper (person who puts explosive in the blood so when they clap hard they explode). Lev plans to blow up the "Chop house" to save the unwinds he is with two others. When he discovers that Connor and Risa are there and about to be unwound he decided to speed up his plans. He tells the others that they will have to do it soon makeing up the excuse that they have been discovered. However they do not initiate there plan before Roland is unwound. We get to see the whole process from Roland's perspective and it is utterly terrifying. The next day lev fails to get away to the chop house and the other clappers blow it up without him. But Connor and Risa are both caught in the explosion. Lev even though explosives still run through his veins rushes to help.</p>
    <p class="card-bg-subtitle">Falling Action / Resolution</p>
    <p class="no-card">After the explosion Lev and Connor both get injury's. Ironically to Connors dismay his arm is replaced by roland's the nurse gives him and id she found of a security gard. Risa is unable to walk anymore which works in here favor because they cannot unwind those with disability's. They both return to the graveyard to keep the place running now that the admiral cannot. They are extracting the explosive from Lev when Pastor Dan comes to visit him. He tells lev that the public is curious about lev. "The Clapper who never clapped". He says that the corts will likely favor him and not unwind him. However the Cadler's have disowned him his brother however is willing to take him in. Pastor Dan finishes by saying that he has chosen to believe in a god who doesn't support unwinding</p>
  </div>
</template>

<style scoped>

</style>
